// src/components/dialogs/LoginDialog.tsx
import React, { useState } from 'react';
import { LogIn, X, Key, User, Shield } from 'lucide-react';
import { ServerProfile } from '../../types';

interface LoginDialogProps {
  profile: ServerProfile;
  onLogin: (credentials: { username: string; token: string }) => void;
  onClose: () => void;
}

export const LoginDialog: React.FC<LoginDialogProps> = ({ profile, onLogin, onClose }) => {
  const [username, setUsername] = useState('admin');
  const [token, setToken] = useState('demo-token-123');

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onLogin({ username, token });
    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-xs p-4 animate-fade-in text-xs">
      <div className="w-full max-w-sm bg-[rgb(var(--color-surface-dialog))] border border-[rgb(var(--color-border-base))] rounded-xl shadow-2xl overflow-hidden flex flex-col">
        <div className="flex items-center justify-between px-4 py-3 border-b border-[rgb(var(--color-border-base))] bg-[rgb(var(--color-surface-muted))]">
          <div className="flex items-center gap-2">
            <LogIn className="w-4 h-4 text-blue-500" />
            <h3 className="font-semibold text-sm text-[rgb(var(--color-text-base))]">
              Connect to {profile.name}
            </h3>
          </div>
          <button
            onClick={onClose}
            className="p-1 rounded hover:bg-[rgb(var(--color-surface-hover))] text-[rgb(var(--color-text-muted))]"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="p-4 flex flex-col gap-3">
          <p className="text-[11px] text-[rgb(var(--color-text-muted))]">
            Authenticate session against broker endpoint: <br />
            <span className="font-mono text-[10px] text-blue-500">{profile.brokerUrl}</span>
          </p>

          <div>
            <label className="block text-[11px] font-medium text-[rgb(var(--color-text-muted))] mb-1">
              Username / Client ID
            </label>
            <div className="relative flex items-center">
              <User className="w-3.5 h-3.5 absolute left-2.5 text-[rgb(var(--color-text-subtle))]" />
              <input
                type="text"
                required
                value={username}
                onChange={(e) => setUsername(e.target.value)}
                className="w-full pl-8 pr-3 py-1.5 rounded-lg bg-[rgb(var(--color-surface-input))] border border-[rgb(var(--color-border-input))] text-xs text-[rgb(var(--color-text-base))] outline-none focus:ring-1 focus:ring-[rgb(var(--color-accent-text))]"
              />
            </div>
          </div>

          <div>
            <label className="block text-[11px] font-medium text-[rgb(var(--color-text-muted))] mb-1">
              Secret Key / Auth Token
            </label>
            <div className="relative flex items-center">
              <Key className="w-3.5 h-3.5 absolute left-2.5 text-[rgb(var(--color-text-subtle))]" />
              <input
                type="password"
                required
                value={token}
                onChange={(e) => setToken(e.target.value)}
                className="w-full pl-8 pr-3 py-1.5 rounded-lg bg-[rgb(var(--color-surface-input))] border border-[rgb(var(--color-border-input))] text-xs text-[rgb(var(--color-text-base))] outline-none font-mono"
              />
            </div>
          </div>

          <div className="flex items-center justify-end gap-2 pt-3 border-t border-[rgb(var(--color-border-base))]">
            <button
              type="button"
              onClick={onClose}
              className="px-3 py-1.5 rounded-lg border border-[rgb(var(--color-border-base))] hover:bg-[rgb(var(--color-surface-hover))] text-[rgb(var(--color-text-base))]"
            >
              Cancel
            </button>
            <button
              type="submit"
              className="flex items-center gap-1.5 px-4 py-1.5 rounded-lg bg-[rgb(var(--color-accent-bg))] text-[rgb(var(--color-accent-text))] font-medium hover:opacity-90"
            >
              <Shield className="w-3.5 h-3.5" />
              <span>Authenticate & Mount</span>
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

// src/components/login-dialog/login-dialog.component.ts
import { Component, ChangeDetectionStrategy, input, output, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ServerProfile } from '../../models/server-profile.model.js';

@Component({
  selector: 'app-login-dialog',
  imports: [CommonModule],
  templateUrl: './login-dialog.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class LoginDialogComponent {
  profile = input.required<ServerProfile>();
  close = output<void>();
  submitLogin = output<{ username: string, password: string }>();

  username = signal('');
  password = signal('');

  onUsernameChange(event: Event): void {
    this.username.set((event.target as HTMLInputElement).value);
  }

  onPasswordChange(event: Event): void {
    this.password.set((event.target as HTMLInputElement).value);
  }

  onSubmit(): void {
    if (this.username().trim() && this.password().trim()) {
      this.submitLogin.emit({ username: this.username(), password: this.password() });
    }
  }

  onCancel(): void {
    this.close.emit();
  }
}

<div class="fixed inset-0 bg-black bg-opacity-75 z-[60] flex items-center justify-center p-4" (click)="onCancel()">
  <div class="bg-[rgb(var(--color-surface-dialog))] rounded-lg shadow-xl w-full max-w-md" (click)="$event.stopPropagation()">
    <div class="p-4 border-b border-[rgb(var(--color-border-base))]">
      <h3 class="text-lg font-semibold text-[rgb(var(--color-text-base))]">Connect to {{ profile().name }}</h3>
    </div>
    <div class="p-6 space-y-4">
        <p class="text-sm text-[rgb(var(--color-text-subtle))]">Enter your credentials to mount this server profile.</p>
        <div>
            <label for="loginUsername" class="block text-sm font-medium text-[rgb(var(--color-text-muted))]">Username</label>
            <input 
                type="text" 
                id="loginUsername" 
                [value]="username()" 
                (input)="onUsernameChange($event)" 
                autocomplete="username"
                class="mt-1 block w-full px-3 py-2 bg-[rgb(var(--color-surface))] border border-[rgb(var(--color-border-muted))] rounded-md shadow-sm focus:outline-none focus:ring-[rgb(var(--color-accent-ring))] focus:border-[rgb(var(--color-accent-ring))] sm:text-sm">
        </div>
        <div>
            <label for="loginPassword" class="block text-sm font-medium text-[rgb(var(--color-text-muted))]">Password</label>
            <input 
                type="password" 
                id="loginPassword" 
                [value]="password()" 
                (input)="onPasswordChange($event)" 
                (keydown.enter)="onSubmit()"
                autocomplete="current-password"
                class="mt-1 block w-full px-3 py-2 bg-[rgb(var(--color-surface))] border border-[rgb(var(--color-border-muted))] rounded-md shadow-sm focus:outline-none focus:ring-[rgb(var(--color-accent-ring))] focus:border-[rgb(var(--color-accent-ring))] sm:text-sm">
        </div>
    </div>
    <div class="px-6 py-3 bg-[rgb(var(--color-surface-muted))] flex justify-end items-center space-x-2 rounded-b-lg">
      <button (click)="onCancel()" class="px-4 py-2 bg-[rgb(var(--color-surface-hover))] text-[rgb(var(--color-text-base))] rounded-md hover:bg-[rgb(var(--color-border-base))] transition-colors font-semibold text-sm">
        Cancel
      </button>
      <button (click)="onSubmit()" class="px-4 py-2 bg-[rgb(var(--color-accent-solid-bg))] text-[rgb(var(--color-text-inverted))] rounded-md hover:bg-[rgb(var(--color-accent-solid-bg-hover))] transition-colors font-semibold text-sm disabled:bg-[rgb(var(--color-disabled-bg))]" [disabled]="!username().trim() || !password().trim()">
        Log In
      </button>
    </div>
  </div>
</div>
