// src/components/toasts/toasts.component.ts
import { Component, ChangeDetectionStrategy, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ToastService } from '../../services/toast.service.js';

@Component({
  selector: 'app-toasts',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './toasts.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ToastsComponent {
  toastService = inject(ToastService);

  removeToast(id: number): void {
    this.toastService.remove(id);
  }
}

<div class="fixed bottom-4 right-4 z-[100] flex flex-col items-end space-y-2">
  @for (toast of toastService.toasts(); track toast.id) {
    <div 
      class="flex items-center w-full max-w-xs p-4 space-x-4 rtl:space-x-reverse rounded-lg shadow-lg bg-[rgb(var(--color-surface-dialog))] ring-1 ring-black/5 dark:ring-white/10 animate-slide-in-right"
      role="alert">
      
      <!-- Icon based on type -->
      @if (toast.type === 'success') {
        <div class="inline-flex items-center justify-center flex-shrink-0 w-8 h-8 text-[rgb(var(--color-status-green-text))] bg-[rgb(var(--color-status-green-bg))] rounded-lg">
          <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
            <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm3.707 8.207-4 4a1 1 0 0 1-1.414 0l-2-2a1 1 0 0 1 1.414-1.414L9 10.586l3.293-3.293a1 1 0 0 1 1.414 1.414Z"/>
          </svg>
          <span class="sr-only">Check icon</span>
        </div>
      }

      <!-- Message -->
      <div class="ms-3 text-sm font-normal text-[rgb(var(--color-text-base))]">{{ toast.message }}</div>

      <!-- Close Button -->
      <button (click)="removeToast(toast.id)" type="button" class="ms-auto -mx-1.5 -my-1.5 rounded-lg focus:ring-2 focus:ring-[rgb(var(--color-border-muted))] p-1.5 hover:bg-[rgb(var(--color-surface-hover))] inline-flex items-center justify-center h-8 w-8 text-[rgb(var(--color-text-subtle))] hover:text-[rgb(var(--color-text-base))]" aria-label="Close">
        <span class="sr-only">Close</span>
        <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
        </svg>
      </button>
    </div>
  }
</div>

// src/components/Toasts.tsx
import React from 'react';
import { ToastMessage } from '../types';
import { CheckCircle2, AlertCircle, Info, X } from 'lucide-react';

interface ToastsProps {
  toasts: ToastMessage[];
  onDismiss: (id: string) => void;
}

export const Toasts: React.FC<ToastsProps> = ({ toasts, onDismiss }) => {
  if (toasts.length === 0) return null;

  return (
    <div className="fixed bottom-10 right-4 z-50 flex flex-col gap-2 max-w-sm w-full pointer-events-none">
      {toasts.map((toast) => {
        let bg = 'bg-[rgb(var(--color-surface-dialog))] text-[rgb(var(--color-text-base))] border-[rgb(var(--color-border-base))]';
        let icon = <Info className="w-5 h-5 text-blue-500 flex-shrink-0" />;

        if (toast.type === 'success') {
          icon = <CheckCircle2 className="w-5 h-5 text-green-500 flex-shrink-0" />;
        } else if (toast.type === 'error') {
          icon = <AlertCircle className="w-5 h-5 text-red-500 flex-shrink-0" />;
        } else if (toast.type === 'warning') {
          icon = <AlertCircle className="w-5 h-5 text-yellow-500 flex-shrink-0" />;
        }

        return (
          <div
            key={toast.id}
            className={`pointer-events-auto flex items-center justify-between p-3 rounded-lg border shadow-lg transition-all animate-slide-in-right ${bg}`}
          >
            <div className="flex items-center gap-2.5 min-w-0 pr-2">
              {icon}
              <span className="text-sm font-medium break-words">{toast.text}</span>
            </div>
            <button
              onClick={() => onDismiss(toast.id)}
              className="p-1 rounded hover:bg-[rgb(var(--color-surface-hover))] text-[rgb(var(--color-text-subtle))] hover:text-[rgb(var(--color-text-base))]"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        );
      })}
    </div>
  );
};
