// src/components/local-config-dialog/local-config-dialog.component.ts
import { Component, ChangeDetectionStrategy, output, inject, signal, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LocalConfig, LocalConfigService } from '../../services/local-config.service.js';

@Component({
  selector: 'app-local-config-dialog',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './local-config-dialog.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class LocalConfigDialogComponent implements OnInit {
  private localConfigService = inject(LocalConfigService);
  
  close = output<void>();
  save = output<LocalConfig>();

  formState = signal<LocalConfig>({ sessionName: '', defaultImageUrl: '', logBrokerMessages: false });

  ngOnInit(): void {
    this.formState.set(this.localConfigService.currentConfig());
  }

  onValueChange(event: Event, field: 'sessionName' | 'defaultImageUrl'): void {
    const value = (event.target as HTMLInputElement).value;
    this.formState.update(state => ({ ...state, [field]: value }));
  }

  onCheckboxChange(event: Event, field: 'logBrokerMessages'): void {
    const checked = (event.target as HTMLInputElement).checked;
    this.formState.update(state => ({ ...state, [field]: checked }));
  }

  onSave(): void {
    this.save.emit(this.formState());
  }
}

<div class="fixed inset-0 bg-black bg-opacity-75 z-50 flex items-center justify-center p-4" (click)="close.emit()">
  <div class="bg-[rgb(var(--color-surface-dialog))] rounded-lg shadow-xl w-full max-w-lg" (click)="$event.stopPropagation()">
    
    <div class="p-4 border-b border-[rgb(var(--color-border-base))] flex justify-between items-center">
      <h3 class="text-lg font-semibold text-[rgb(var(--color-text-base))]">Local Configuration</h3>
      <button (click)="close.emit()" class="p-1 rounded-full hover:bg-[rgb(var(--color-surface-hover))] text-[rgb(var(--color-text-muted))]">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
        </svg>
      </button>
    </div>
    
    <div class="p-6 space-y-6">
      <div>
        <label for="sessionName" class="block text-sm font-medium text-[rgb(var(--color-text-muted))]">Local Session Name</label>
        <p class="text-xs text-[rgb(var(--color-text-subtle))] mt-1">The name for the file system stored in this browser session.</p>
        <input type="text" id="sessionName" [value]="formState().sessionName" (input)="onValueChange($event, 'sessionName')"
              class="mt-2 block w-full px-3 py-2 bg-[rgb(var(--color-surface))] border border-[rgb(var(--color-border-muted))] rounded-md shadow-sm focus:outline-none focus:ring-[rgb(var(--color-accent-ring))] focus:border-[rgb(var(--color-accent-ring))] sm:text-sm">
      </div>

      <div>
        <label for="defaultImageUrl" class="block text-sm font-medium text-[rgb(var(--color-text-muted))]">Default Image Server URL</label>
        <p class="text-xs text-[rgb(var(--color-text-subtle))] mt-1">The image server used for the Local Session and as a fallback for remote profiles without a specified image server.</p>
        <input type="text" id="defaultImageUrl" [value]="formState().defaultImageUrl" (input)="onValueChange($event, 'defaultImageUrl')" placeholder="http://..."
              class="mt-2 block w-full px-3 py-2 bg-[rgb(var(--color-surface))] border border-[rgb(var(--color-border-muted))] rounded-md shadow-sm focus:outline-none focus:ring-[rgb(var(--color-accent-ring))] focus:border-[rgb(var(--color-accent-ring))] sm:text-sm">
      </div>

      <div class="pt-2">
        <div class="relative flex items-start">
          <div class="flex h-6 items-center">
            <input id="logBrokerMessages" type="checkbox" [checked]="formState().logBrokerMessages" (change)="onCheckboxChange($event, 'logBrokerMessages')"
                  class="h-4 w-4 rounded border-[rgb(var(--color-border-muted))] text-[rgb(var(--color-accent-text))] focus:ring-[rgb(var(--color-accent-ring))] bg-[rgb(var(--color-surface))]">
          </div>
          <div class="ml-3 text-sm leading-6">
            <label for="logBrokerMessages" class="font-medium text-[rgb(var(--color-text-muted))]">Enable Broker Logging</label>
            <p class="text-xs text-[rgb(var(--color-text-subtle))]">Log all service broker requests and responses to the developer console.</p>
          </div>
        </div>
      </div>
    </div>

    <div class="px-6 py-3 bg-[rgb(var(--color-surface-muted))] flex justify-end items-center space-x-2 rounded-b-lg">
      <button (click)="close.emit()" class="px-4 py-2 bg-[rgb(var(--color-surface-hover))] text-[rgb(var(--color-text-base))] rounded-md hover:bg-[rgb(var(--color-border-base))] transition-colors font-semibold text-sm">
        Cancel
      </button>
      <button (click)="onSave()" class="px-4 py-2 bg-[rgb(var(--color-accent-solid-bg))] text-[rgb(var(--color-text-inverted))] rounded-md hover:bg-[rgb(var(--color-accent-solid-bg-hover))] transition-colors font-semibold text-sm disabled:bg-[rgb(var(--color-disabled-bg))]" [disabled]="!formState().sessionName.trim() || !formState().defaultImageUrl.trim()">
        Save
      </button>
    </div>

  </div>
</div>

// src/components/dialogs/LocalConfigDialog.tsx
import React, { useState } from 'react';
import { Settings, X, Save } from 'lucide-react';

interface LocalConfigDialogProps {
  sessionName: string;
  defaultImageUrl: string;
  onSave: (sessionName: string, defaultImageUrl: string) => void;
  onClose: () => void;
}

export const LocalConfigDialog: React.FC<LocalConfigDialogProps> = ({
  sessionName,
  defaultImageUrl,
  onSave,
  onClose,
}) => {
  const [name, setName] = useState(sessionName);
  const [imageUrl, setImageUrl] = useState(defaultImageUrl);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!name.trim()) return;
    onSave(name.trim(), imageUrl.trim());
    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-xs p-4 animate-fade-in text-xs">
      <div className="w-full max-w-md bg-[rgb(var(--color-surface-dialog))] border border-[rgb(var(--color-border-base))] rounded-xl shadow-2xl overflow-hidden flex flex-col">
        <div className="flex items-center justify-between px-4 py-3 border-b border-[rgb(var(--color-border-base))] bg-[rgb(var(--color-surface-muted))]">
          <div className="flex items-center gap-2">
            <Settings className="w-4 h-4 text-emerald-500" />
            <h3 className="font-semibold text-sm text-[rgb(var(--color-text-base))]">
              Local Session Configuration
            </h3>
          </div>
          <button
            onClick={onClose}
            className="p-1 rounded hover:bg-[rgb(var(--color-surface-hover))] text-[rgb(var(--color-text-muted))]"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="p-4 flex flex-col gap-4">
          <div>
            <label className="block text-[11px] font-medium text-[rgb(var(--color-text-muted))] mb-1">
              Virtual Session Root Name
            </label>
            <input
              type="text"
              required
              value={name}
              onChange={(e) => setName(e.target.value)}
              placeholder="e.g. Local Session"
              className="w-full px-3 py-1.5 rounded-lg bg-[rgb(var(--color-surface-input))] border border-[rgb(var(--color-border-input))] text-xs text-[rgb(var(--color-text-base))] outline-none focus:ring-1 focus:ring-[rgb(var(--color-accent-text))]"
            />
          </div>

          <div>
            <label className="block text-[11px] font-medium text-[rgb(var(--color-text-muted))] mb-1">
              Default Image Service URL
            </label>
            <input
              type="url"
              value={imageUrl}
              onChange={(e) => setImageUrl(e.target.value)}
              placeholder="https://picsum.photos/seed"
              className="w-full px-3 py-1.5 rounded-lg bg-[rgb(var(--color-surface-input))] border border-[rgb(var(--color-border-input))] text-xs text-[rgb(var(--color-text-base))] outline-none font-mono"
            />
          </div>

          <div className="flex items-center justify-end gap-2 pt-3 border-t border-[rgb(var(--color-border-base))]">
            <button
              type="button"
              onClick={onClose}
              className="px-3 py-1.5 rounded-lg border border-[rgb(var(--color-border-base))] hover:bg-[rgb(var(--color-surface-hover))] text-[rgb(var(--color-text-base))]"
            >
              Cancel
            </button>
            <button
              type="submit"
              className="flex items-center gap-1.5 px-4 py-1.5 rounded-lg bg-[rgb(var(--color-accent-bg))] text-[rgb(var(--color-accent-text))] font-medium hover:opacity-90"
            >
              <Save className="w-3.5 h-3.5" />
              <span>Save Configuration</span>
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};
